In [71]:
import numpy as np

# # 假设 W 是一个 3x3 的矩阵
# W = np.array([[0.1, 0.2, 0.3],
#               [0.4, 0.5, 0.6],
#               [0.7, 0.8, 0.9]])

# G = np.array([[5, 2, 0.3],
#               [4, 15, 0.6]])

# # grads 是一个包含 W 同样形状的全零矩阵的列表
# grads = [np.zeros_like(W)]
# print(np.zeros_like(W))
# print(np.zeros_like(G))
# print(grads)

# dw, = grads
# dw

In [72]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None
        print(self.grads)

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out

    def backward(self, dout):
        dW, = self.grads
        # dW[...] = 0 #dW[...] = 0 将 dW（即全零矩阵）重置为全零，确保每次进行反向传播时梯度是清零的。
        print(dW)
        
        # if GPU:
        #     np.scatter_add(dW, self.idx, dout)
        # else:
        #     np.add.at(dW, self.idx, dout)
        np.add.at(dW, self.idx, dout)
        print(dW)
        return None

In [73]:
W = np.array([[0.1, 0.2, 0.3],  # 词 0
              [0.4, 0.5, 0.6],  # 词 1
              [0.7, 0.8, 0.9],  # 词 2
              [1.0, 1.1, 1.2]]) # 词 3

dout = np.array([[0.01, 0.02, 0.03],  # 对词 0 的梯度
                 [0.04, 0.05, 0.06]]) # 对词 2 的梯度

dout2 = np.array([[11, 0.02, 0.03],  # 对词 0 的梯度
                 [0.04, 0.05, 0.06]]) # 对词 2 的梯度

out = [0, 2]

model = Embedding(W)
out = model.forward(out)
print(out)

[array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])]
[[0.1 0.2 0.3]
 [0.7 0.8 0.9]]


In [74]:
model.backward(dout)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.01 0.02 0.03]
 [0.   0.   0.  ]
 [0.04 0.05 0.06]
 [0.   0.   0.  ]]


In [75]:
out2 = model.backward(dout2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[11.    0.02  0.03]
 [ 0.    0.    0.  ]
 [ 0.04  0.05  0.06]
 [ 0.    0.    0.  ]]
