In [6]:
import numpy as np
D= 8
N = 7
x = np.random.randn(1,D)
y=np.repeat(x,N,axis=0) #7行8列
# z=np.repeat(x,N,axis=1)
x,y

(array([[-1.03536552, -1.40302164,  0.2423318 , -0.93771918, -0.2353573 ,
         -0.08717134,  0.19309243, -0.96340202]]),
 array([[-1.03536552, -1.40302164,  0.2423318 , -0.93771918, -0.2353573 ,
         -0.08717134,  0.19309243, -0.96340202],
        [-1.03536552, -1.40302164,  0.2423318 , -0.93771918, -0.2353573 ,
         -0.08717134,  0.19309243, -0.96340202],
        [-1.03536552, -1.40302164,  0.2423318 , -0.93771918, -0.2353573 ,
         -0.08717134,  0.19309243, -0.96340202],
        [-1.03536552, -1.40302164,  0.2423318 , -0.93771918, -0.2353573 ,
         -0.08717134,  0.19309243, -0.96340202],
        [-1.03536552, -1.40302164,  0.2423318 , -0.93771918, -0.2353573 ,
         -0.08717134,  0.19309243, -0.96340202],
        [-1.03536552, -1.40302164,  0.2423318 , -0.93771918, -0.2353573 ,
         -0.08717134,  0.19309243, -0.96340202],
        [-1.03536552, -1.40302164,  0.2423318 , -0.93771918, -0.2353573 ,
         -0.08717134,  0.19309243, -0.96340202]]))

In [7]:
dy = np.random.randn(N,D) #7行8列
dy
dx = np.sum(dy,axis=0,keepdims=True)

In [10]:
# coding: utf-8
import numpy as np


def load_data(seed=1984):
    np.random.seed(seed)
    N = 100  # 各类的样本数
    DIM = 2  # 数据的元素个数
    CLS_NUM = 3  # 类别数

    x = np.zeros((N*CLS_NUM, DIM))
    t = np.zeros((N*CLS_NUM, CLS_NUM), dtype=int)

    for j in range(CLS_NUM):
        for i in range(N):#N*j, N*(j+1)):
            rate = i / N
            radius = 1.0*rate
            theta = j*4.0 + 4.0*rate # + np.random.randn()*0.2
            print('theta=',theta)
            ix = N*j + i
            x[ix] = np.array([radius*np.sin(theta),
                              radius*np.cos(theta)]).flatten()
            t[ix, j] = 1
            print(j,'-----',rate,np.sin(theta),np.cos(theta))

    return x, t

load_data()

theta= 0.0
0 ----- 0.0 0.0 1.0
theta= 0.04
0 ----- 0.01 0.03998933418663416 0.9992001066609779
theta= 0.08
0 ----- 0.02 0.0799146939691727 0.9968017063026194
theta= 0.12
0 ----- 0.03 0.11971220728891936 0.9928086358538663
theta= 0.16
0 ----- 0.04 0.15931820661424598 0.9872272833756269
theta= 0.2
0 ----- 0.05 0.19866933079506122 0.9800665778412416
theta= 0.24
0 ----- 0.06 0.23770262642713458 0.9713379748520296
theta= 0.28
0 ----- 0.07 0.27635564856411376 0.9610554383107709
theta= 0.32
0 ----- 0.08 0.31456656061611776 0.9492354180824408
theta= 0.36
0 ----- 0.09 0.35227423327508994 0.9358968236779348
theta= 0.4
0 ----- 0.1 0.3894183423086505 0.9210609940028851
theta= 0.44
0 ----- 0.11 0.4259394650659996 0.9047516632199634
theta= 0.48
0 ----- 0.12 0.46177917554148284 0.8869949227792842
theta= 0.52
0 ----- 0.13 0.49688013784373675 0.8678191796776499
theta= 0.56
0 ----- 0.14 0.5311861979208834 0.8472551110134161
theta= 0.6
0 ----- 0.15 0.5646424733950354 0.8253356149096783
theta= 0.64
0 ----

(array([[ 0.00000000e+00,  0.00000000e+00],
        [ 3.99893342e-04,  9.99200107e-03],
        [ 1.59829388e-03,  1.99360341e-02],
        [ 3.59136622e-03,  2.97842591e-02],
        [ 6.37272826e-03,  3.94890913e-02],
        [ 9.93346654e-03,  4.90033289e-02],
        [ 1.42621576e-02,  5.82802785e-02],
        [ 1.93448954e-02,  6.72738807e-02],
        [ 2.51653248e-02,  7.59388334e-02],
        [ 3.17046810e-02,  8.42307141e-02],
        [ 3.89418342e-02,  9.21060994e-02],
        [ 4.68533412e-02,  9.95226830e-02],
        [ 5.54135011e-02,  1.06439391e-01],
        [ 6.45944179e-02,  1.12816493e-01],
        [ 7.43660677e-02,  1.18615716e-01],
        [ 8.46963710e-02,  1.23800342e-01],
        [ 9.55512706e-02,  1.28335321e-01],
        [ 1.06894814e-01,  1.32187362e-01],
        [ 1.18689241e-01,  1.35325031e-01],
        [ 1.30895075e-01,  1.37718842e-01],
        [ 1.43471218e-01,  1.39341342e-01],
        [ 1.56375055e-01,  1.40167193e-01],
        [ 1.69562553e-01,  1.401

In [ ]:
def load_data2(seed=1998):
    np.random.seed(seed)
    N = 100
    DIM = 2
    CLS_NUM = 3

    x = np.zeros(N*CLS_NUM,DIM)
    t = np.zeros((N*CLS_NUM,CLS_NUM),dtype=int)

    for j in range(CLS_NUM):
        for i in range(N):
            rate = i/N
            radius = 1.0*rate
            theta = j*4.0 + 4.0*rate+np.random.randn()*0.2